export { HeroSection } from "./HeroSection"
export { AboutSection } from "./AboutSection"
export { SkillsSection } from "./SkillsSection"
export { ProjectsSection } from "./ProjectsSection"
export { ExperienceSection } from "./ExperienceSection"
export { StrengthsSection } from "./StrengthsSection"
export { ContactSection } from "./ContactSection"
